name: Deploy OpenTofu to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
      pull-requests: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Extract Tag
        id: vars
        run: echo "tag=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Check for app changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            app:
              - 'app/**'
              - 'Dockerfile'

#      - name: Configure Docker
#        if: steps.changes.outputs.app == 'true'
#        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

#      - name: Build and Push Docker image
#        if: steps.changes.outputs.app == 'true'
#        run: |
#          PROJECT_LOWER=$(echo "${{ env.GCP_PROJECT }}" | tr '[:upper:]' '[:lower:]')
#          REPO_LOWER=$(echo "${{ secrets.GCP_AR_REPO }}" | tr '[:upper:]' '[:lower:]')
#          IMAGE="europe-west1-docker.pkg.dev/$PROJECT_LOWER/$REPO_LOWER/run-tofu-api:${{ steps.vars.outputs.tag }}"
#          docker build -t $IMAGE .
#          docker push $IMAGE
#          echo "IMAGE_URL=$IMAGE" >> $GITHUB_ENV
#        env:
#          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

#      - name: Update dev.tf with new image tag
#        if: steps.changes.outputs.app == 'true'
#        run: |
#          sed -i "s|image[[:space:]]*=[[:space:]]*\".*\"|image        = \"${{ env.IMAGE_URL }}\"|g" infra/iac/dev.tf
#          git config --global user.name "github-actions[bot]"
#          git config --global user.email "github-actions[bot]@users.noreply.github.com"
#          git add infra/iac/dev.tf
#          git commit -m "Deploy dev environment to sha ${{ steps.vars.outputs.tag }} [skip ci]" || echo "No changes to commit"
#          git push

      - name: OpenTofu Init
        run: tofu init
        working-directory: ./infra/iac

      - name: OpenTofu Apply
        run: tofu apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT }}" -var="github_repository=${{ github.repository }}"
        working-directory: ./infra/iac

#      - name: Update live.tf for PR
#        if: steps.changes.outputs.app == 'true'
#        run: |
#          sed -i "s|image[[:space:]]*=[[:space:]]*\".*\"|image        = \"${{ env.IMAGE_URL }}\"|g" infra/iac/live.tf

#      - name: Create Pull Request for Live Promotion
#        if: steps.changes.outputs.app == 'true'
#        uses: peter-evans/create-pull-request@v6
#        with:
#          commit-message: "Promote dev image to live (${{ steps.vars.outputs.tag }})"
#          branch: "promote-live-${{ steps.vars.outputs.tag }}"
#          title: "🚀 Promote image to Live: ${{ steps.vars.outputs.tag }}"
#          body: "Automatically generated PR to promote the newly built Dev image to the Live environment. Merge this PR to trigger the live deployment."
#          base: main
#          add-paths: infra/iac/live.tf
